### ISSUE TITLE
TypeError: employeesAddon.gotoFlow is not a function

### ISSUE THREAD

**Issue by MisterEquis** [leifermendez/bot-ws-openai#2]
Al iniciar el proyecto, luego de instalar package de NPM y colocar las respectivas API_KEYS en el .ENV, cuando envío un audio en el chat, lo convierte a voz pero luego me da este error. 

Por lo que pude evaluar lo da en la `línea 63 de app.js`
` employeesAddon.gotoFlow(empleado, ctxFn);`

**Comment by ferguarino** [comment]
Hola MisterEquis, me paso lo mismo, subieron el codigo sin revisar lamentablemente...el error esta en que gotoFlow no es una funcion, la que es la funcion es _gotoFlow o sea e mismo nombre con un guion bajo _ antes con eso te va a funcionar, pero luego esta tirando otro error relacionado con ffmpeg que estoy resolviendo. Espero te sirva!

**Comment by leifermendez** [comment]
fix
